DROP TABLE USERS;
DROP TABLE CUSTOMERS;
DROP TABLE PRODUCTS;
DROP TABLE ORDER_REGISTER;


CREATE TABLE USERS
(
	USER_ID int NOT NULL auto_increment,
    PRIMARY KEY(USER_ID),
	USER_NAME VARCHAR(20),
    USER_PASS VARCHAR(20),
    USER_ROLE VARCHAR(20)
)
auto_increment=1001;

INSERT INTO USERS(USER_NAME, USER_PASS, USER_ROLE) VALUES('admin', 'admin123', 'admin');
commit;

select * from users;


CREATE TABLE CUSTOMERS
(
	CUST_ID int NOT NULL auto_increment,
    PRIMARY KEY(CUST_ID),
	CUST_F_NAME VARCHAR(20),
    CUST_L_NAME VARCHAR(20),
    CUST_EMAIL VARCHAR(100),
    CUST_MOB VARCHAR(10)    
)
auto_increment=2001;

select * from CUSTOMERS;

CREATE TABLE PRODUCTS
(
	PDT_ID int NOT NULL auto_increment,
    PRIMARY KEY(PDT_ID),
	PDT_NAME VARCHAR(20),
    PDT_CATEGORY VARCHAR(20),
    PDT_COST VARCHAR(10),
    PDT_ORI_COUNTRY VARCHAR(30)    
)
auto_increment=3001;

INSERT INTO PRODUCTS(PDT_NAME, PDT_CATEGORY, PDT_COST, PDT_ORI_COUNTRY) VALUES ('BLAZE SHOES', 'RUNNING', '1250','INDIA');
INSERT INTO PRODUCTS(PDT_NAME, PDT_CATEGORY, PDT_COST, PDT_ORI_COUNTRY) VALUES ('SOFT PUPPIES', 'KIDS', '2250','USA');
INSERT INTO PRODUCTS(PDT_NAME, PDT_CATEGORY, PDT_COST, PDT_ORI_COUNTRY) VALUES ('POWER SHOES', 'GYM', '1100','INDIA');
INSERT INTO PRODUCTS(PDT_NAME, PDT_CATEGORY, PDT_COST, PDT_ORI_COUNTRY) VALUES ('AMAZE SHOES', 'TREKKING', '4500','THAILAND');
INSERT INTO PRODUCTS(PDT_NAME, PDT_CATEGORY, PDT_COST, PDT_ORI_COUNTRY) VALUES ('PARTY SHOES', 'PARTY', '3500','FRANCE');
INSERT INTO PRODUCTS(PDT_NAME, PDT_CATEGORY, PDT_COST, PDT_ORI_COUNTRY) VALUES ('CASUAL SHOES', 'CASUAL', '650','INDIA');
INSERT INTO PRODUCTS(PDT_NAME, PDT_CATEGORY, PDT_COST, PDT_ORI_COUNTRY) VALUES ('ALL WEATHER SHOES', 'ALL-WEATHER', '990','INDIA');

SELECT * FROM PRODUCTS;


CREATE TABLE ORDER_REGISTER
(
	ORD_ID int NOT NULL auto_increment,
    PRIMARY KEY(ORD_ID),
    ORD_BILL_NO INT,
    ORD_DATE DATETIME,
	ORD_PDT_NAME VARCHAR(20),
    ORD_PDT_CATEGORY VARCHAR(20),
    ORD_QTY int,
    ORD_CUST_F_NAME VARCHAR(100),
    ORD_CUST_L_NAME VARCHAR(100),
    ORD_CUST_EMAIL VARCHAR(100),
    ORD_CUST_MOB VARCHAR(10),
    ORD_AMOUNT DECIMAL
)
auto_increment=4001;

INSERT INTO ORDER_REGISTER(ORD_BILL_NO, ORD_DATE, ORD_PDT_NAME, ORD_PDT_CATEGORY, ORD_QTY, ORD_CUST_F_NAME, ORD_CUST_L_NAME, ORD_CUST_EMAIL, ORD_CUST_MOB, ORD_AMOUNT) 
VALUES (101, sysdate(), 'BLAZE SHOES', 'RUNNING', 10, 'JOHN', 'WICK', 'j.wick@gmail.com', '9898987452', 12500);
INSERT INTO ORDER_REGISTER(ORD_BILL_NO, ORD_DATE, ORD_PDT_NAME, ORD_PDT_CATEGORY, ORD_QTY, ORD_CUST_F_NAME, ORD_CUST_L_NAME, ORD_CUST_EMAIL, ORD_CUST_MOB, ORD_AMOUNT) 
VALUES (102, sysdate(), 'AMAZE SHOES', 'TREKKING', 15, 'NICHOLAS', 'CAGE', 'n.cage@gmail.com', '9863524789', 67500);
INSERT INTO ORDER_REGISTER(ORD_BILL_NO, ORD_DATE, ORD_PDT_NAME, ORD_PDT_CATEGORY, ORD_QTY, ORD_CUST_F_NAME, ORD_CUST_L_NAME, ORD_CUST_EMAIL, ORD_CUST_MOB, ORD_AMOUNT) 
VALUES (103, sysdate(), 'CASUAL SHOES', 'CASUAL', 2, 'VICKY', 'KALE', 'v.kale@hotmail.com', '9632587412', 1300);
INSERT INTO ORDER_REGISTER(ORD_BILL_NO, ORD_DATE, ORD_PDT_NAME, ORD_PDT_CATEGORY, ORD_QTY, ORD_CUST_F_NAME, ORD_CUST_L_NAME, ORD_CUST_EMAIL, ORD_CUST_MOB, ORD_AMOUNT) 
VALUES (104, sysdate(), 'PARTY SHOES', 'PARTY', 6, 'ANGELINA', 'JOLIE', 'a.jolie@gmail.com', '9517531598', 21000);
INSERT INTO ORDER_REGISTER(ORD_BILL_NO, ORD_DATE, ORD_PDT_NAME, ORD_PDT_CATEGORY, ORD_QTY, ORD_CUST_F_NAME, ORD_CUST_L_NAME, ORD_CUST_EMAIL, ORD_CUST_MOB, ORD_AMOUNT) 
VALUES (105, sysdate(), 'SOFT PUPPIES', 'KIDS', 9, 'BRAD', 'PITT', 'brad.pitt@gmail.com', '9657841523', 20250);
INSERT INTO ORDER_REGISTER(ORD_BILL_NO, ORD_DATE, ORD_PDT_NAME, ORD_PDT_CATEGORY, ORD_QTY, ORD_CUST_F_NAME, ORD_CUST_L_NAME, ORD_CUST_EMAIL, ORD_CUST_MOB, ORD_AMOUNT) 
VALUES (106, sysdate(), 'ALL WEATHER SHOES', 'ALL-WEATHER', 3, 'JIM', 'JACK', 'jim.jack@gmail.com', '9874102365', 2970);
INSERT INTO ORDER_REGISTER(ORD_BILL_NO, ORD_DATE, ORD_PDT_NAME, ORD_PDT_CATEGORY, ORD_QTY, ORD_CUST_F_NAME, ORD_CUST_L_NAME, ORD_CUST_EMAIL, ORD_CUST_MOB, ORD_AMOUNT) 
VALUES (107, sysdate(), 'BLAZE SHOES', 'RUNNING', 2, 'JETHALAL', 'DUBEY', 'j.dubey@gmail.com', '9631234567', 2500);
INSERT INTO ORDER_REGISTER(ORD_BILL_NO, ORD_DATE, ORD_PDT_NAME, ORD_PDT_CATEGORY, ORD_QTY, ORD_CUST_F_NAME, ORD_CUST_L_NAME, ORD_CUST_EMAIL, ORD_CUST_MOB, ORD_AMOUNT) 
VALUES (108, sysdate(), 'BLAZE SHOES', 'RUNNING', 9, 'JACK', 'DAWSON', 'jack.d@rediffmail.com', '9859631257', 11250);

SELECT * FROM ORDER_REGISTER;

SELECT * FROM ORDER_REGISTER where  convert(ORD_DATE, DATE)='2022-02-24' and ORD_PDT_CATEGORY='RUNNING';